### PR TITLE
New features

### PR DESCRIPTION
**Pull request by cpolizzi**

### CODE REVIEW

**Comment by sabre1041** [comment]
@cpolizzi Would you be able to provide steps to test the changes

**Comment by cpolizzi** [comment]
@sabre1041 I can document a manual process to test.  How extensive do we want to get?

**Comment by sabre1041** [comment]
@cpolizzi please disregard my prior statement. After reacquainting myself with the playbooks, I should be good to go. Going to first test #2 and then continue into this one

**Comment by sabre1041** [comment]
@cpolizzi im working on integrating your contribution in with the existing ecosystem. Ignore the conflict as I will be addressing. I am retrieving the following error when testing both my integrated branch as well as isolating your existing PR from the branch in your repository:

```
TASK [cpolizzi_jboss_amq : configure - clustering - retrieve existing static connectors] *****************************************************************************************************************************************************
fatal: [10.9.53.88]: FAILED! => {"changed": false, "msg": "Xpath /conf:configuration/core:core/core:connectors/core:connector does not reference a node!"}
```

Tested with AMQ 7.1.0 broker from Red Hat customer portal

**Review by buuhsmead — COMMENTED** [review]
Would be nice if this could be accepted. Then I can start merging with the stuff I have.

**Comment by cpolizzi** [comment]
@sabre1041 I will look at it this evening. I believe the issue is related to clustering is disabled; which should be perfectly valid. So if this is the case it is certainly a defect.

**Comment by sabre1041** [comment]
@cpolizzi I have integrated your changes as part of 1ecd8b013c1c2a7fa8a6fa9fc524a3b4f0dcce92

Thanks again!

**Pull request closed without merging**
